liquibase:
  change-log: classpath:db.changelog.xml
spring:
  datasource:
    driverClassName: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://localhost:1433/proposals
    username: sa
